import Head from 'next/head'
import styles from '../styles/Home.module.css'
import * as XLSX from "xlsx"
export default function XlsxTest() {
  const handleUpload=async(e)=>{
    var oFile = e.target.files[0];

    var reader = new FileReader();
    var result = {};

    reader.onload = function (e) {
        var data = e.target.result;
        data = new Uint8Array(data);
        var workbook = XLSX.read(data, {type: 'array'});
        console.log(workbook);
        var result = {};
        workbook.SheetNames.forEach(function (sheetName) {
            var roa = XLSX.utils.sheet_to_json(workbook.Sheets[sheetName], {header: 1});
            console.log("roa",roa)
        });
        // see the result, caution: it works after reader event is done.
        console.log(result);
    };
    reader.readAsArrayBuffer(oFile);
  
  
  }
    

  

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Testing Excel to JSON converter
        </h1>
        <div style={{ display: "flex" }}>        <form>
          <input type="file" onChange={handleUpload} />
          <button type="reset">Clear</button>
        </form>
        </div>
      </main>
    </div>
  )
}
